---
deployment:
  tasks:
    - export DEPLOYPATH=/home/z0qzj7w8/www/
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp asset-manifest.json $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp logo192.png $DEPLOYPATH
    - /bin/cp logo512.png $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp service-worker.js $DEPLOYPATH