---
deployment:
  tasks:
    - export DEPLOYPATH=/home/z0qzj7w8/public_html/
    - /bin/cp -R /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/build/static $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/index.html $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/asset-manifest.json $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/favicon.ico $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/logo192.png $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/logo512.png $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/manifest.json $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/robots.txt $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/service-worker.js $DEPLOYPATH