---
deployment:
  tasks:
    - export DEPLOYPATH=/home/z0qzj7w8/public_html/
    - /bin/cp -R /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/build/frangrandedossier/build/static $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/build/frangrandedossier/build/index.html $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/build/frangrandedossier/build/asset-manifest.json $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/build/frangrandedossier/build/favicon.ico $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/build/frangrandedossier/build/logo192.png $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/build/frangrandedossier/build/logo512.png $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/build/frangrandedossier/build/manifest.json $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/build/frangrandedossier/build/robots.txt $DEPLOYPATH
    - /bin/cp /home/z0qzj7w8/repositories/FranGrandeDossier/frangrandedossier/build/frangrandedossier/build/service-worker.js $DEPLOYPATH