name: Build and Deploy
on:
  push:
    branches: [master]  # Replace with your default branch if it's not 'main'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use the node version that matches your development environment
    
    - name: Build React App
      run: |
        npm install
        yarn build
        mv build dist  # Rename the build folder if necessary
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.4.0
      with:
        branch: gh-pages  # The branch you're deploying to
        folder: dist  # The folder you're deploying from
        clean: true  # This cleans out old files from the deployment branch
